# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fa8ZxRXlHwN2azCPpWES0uBCmO8Yy_zI
"""

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

training_set = tf.keras.utils.image_dataset_from_directory(
   '/content/drive/MyDrive/Fruits and Vegetables Recognition System/train2',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(64, 64),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,

)

cnn = tf.keras.models.Sequential()

cnn.add(tf.keras.layers.Conv2D(filters=64, kernel_size=3, activation='relu',input_shape=(64,64,3)))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

cnn.add(tf.keras.layers.Conv2D(filters=64, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2))

cnn.add(tf.keras.layers.Dropout(0.5))

cnn.add(tf.keras.layers.Flatten())

cnn.add(tf.keras.layers.Dense(units=128,activation='relu'))

cnn.add(tf.keras.layers.Dense(units=36,activation='softmax'))

cnn.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

training_history4 = cnn.fit(x=training_set,epochs=30)

cnn.save('trained_model6.h5')

training_history4.history

import json
with open('training_hist5.json','w') as f:
  json.dump(training_history4.history,f)

print(training_history4.history.keys())

print("Training Set Accuracy {} % ".format(training_history4.history['accuracy'][-1]*100))

epochs =[i for i in range(1,31)]
plt.plot(epochs,training_history4.history['accuracy'],color='blue')
plt.xlabel('No of Epochs')
plt.ylabel('Training History')
plt.title('Visualization of Training History')
plt.show()

testing_set = tf.keras.utils.image_dataset_from_directory(
   '/content/drive/MyDrive/Fruits and Vegetables Recognition System/test2',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(64, 64),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,

)

cnn =tf.keras.models.load_model('/content/trained_model6.h5')

import cv2



image_path='/content/drive/MyDrive/Fruits and Vegetables Recognition System/test2/banana/Image_1.jpg'
img= cv2.imread(image_path)
plt.imshow(img)
plt.title('Test Image')
plt.xticks([])
plt.yticks([])
plt.show()

image = tf.keras.preprocessing.image.load_img(image_path,target_size=(64,64))
input_arr=tf.keras.preprocessing.image.img_to_array(image)
input_arr2=np.array([input_arr])
predictions = cnn.predict(input_arr2)

print(predictions[0])
print(max(predictions[0]))

result_index=np.where(predictions[0]==max(predictions[0]))
print(result_index[0])

plt.imshow(img)
plt.title('Test Image')
plt.xticks([])
plt.yticks([])
plt.show()

print("Its is a {}".format(testing_set.class_names[result_index[0][0]]))